In [1]:
import pandas as pd
import numpy as np


In [2]:
df = pd.read_csv('AirBnB.csv')

In [3]:
df.head()

id                                              name  host_id  \
0  2539                Clean & quiet apt home by the park     2787   
1  2595                             Skylit Midtown Castle     2845   
2  3647               THE VILLAGE OF HARLEM....NEW YORK !     4632   
3  3831                   Cozy Entire Floor of Brownstone     4869   
4  5022  Entire Apt: Spacious Studio/Loft by central park     7192   

     host_name neighbourhood_group neighbourhood  latitude  longitude  \
0         John            Brooklyn    Kensington  40.64749  -73.97237   
1     Jennifer           Manhattan       Midtown  40.75362  -73.98377   
2    Elisabeth           Manhattan        Harlem  40.80902  -73.94190   
3  LisaRoxanne            Brooklyn  Clinton Hill  40.68514  -73.95976   
4        Laura           Manhattan   East Harlem  40.79851  -73.94399   

         room_type  price  minimum_nights  number_of_reviews last_review  \
0     Private room    149               1                  9  2018-10-19   
1  Entire home/apt    225               1                 45  2019-05-21   
2     Private room    150               3                  0         NaN   
3  Entire home/apt     89               1                270  2019-07-05   
4  Entire home/apt     80              10                  9  2018-11-19   

   reviews_per_month  calculated_host_listings_count  availability_365  
0               0.21                               6               365  
1               0.38                               2               355  
2                NaN                               1               365  
3               4.64                               1               194  
4               0.10                               1                 0

In [4]:
df.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365'],
      dtype='object')

In [5]:
select_col = [ 
              'neighbourhood_group',
              'room_type',
              'latitude', 
              'longitude',
              'price',
              'minimum_nights', 
              'number_of_reviews',
              'reviews_per_month',
              'calculated_host_listings_count',
              'availability_365' ]

Q1 

In [6]:
df_sel_col = df[select_col]
df_sel_col.isnull().sum()

neighbourhood_group                   0
room_type                             0
latitude                              0
longitude                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [7]:
categorical_columns = list(df.dtypes[df.dtypes == 'object'].index)

for c in categorical_columns:
    df[c] = df[c].str.lower().str.replace(' ', '_')

In [8]:
df_sel_col.reviews_per_month

0        0.21
1        0.38
2         NaN
3        4.64
4        0.10
         ... 
48890     NaN
48891     NaN
48892     NaN
48893     NaN
48894     NaN
Name: reviews_per_month, Length: 48895, dtype: float64

In [9]:
df_sel_col= df_sel_col.fillna(0)

In [10]:
df_sel_col

neighbourhood_group        room_type  latitude  longitude  price  \
0                Brooklyn     Private room  40.64749  -73.97237    149   
1               Manhattan  Entire home/apt  40.75362  -73.98377    225   
2               Manhattan     Private room  40.80902  -73.94190    150   
3                Brooklyn  Entire home/apt  40.68514  -73.95976     89   
4               Manhattan  Entire home/apt  40.79851  -73.94399     80   
...                   ...              ...       ...        ...    ...   
48890            Brooklyn     Private room  40.67853  -73.94995     70   
48891            Brooklyn     Private room  40.70184  -73.93317     40   
48892           Manhattan  Entire home/apt  40.81475  -73.94867    115   
48893           Manhattan      Shared room  40.75751  -73.99112     55   
48894           Manhattan     Private room  40.76404  -73.98933     90   

       minimum_nights  number_of_reviews  reviews_per_month  \
0                   1                  9               0.21   
1                   1                 45               0.38   
2                   3                  0               0.00   
3                   1                270               4.64   
4                  10                  9               0.10   
...               ...                ...                ...   
48890               2                  0               0.00   
48891               4                  0               0.00   
48892              10                  0               0.00   
48893               1                  0               0.00   
48894               7                  0               0.00   

       calculated_host_listings_count  availability_365  
0                                   6               365  
1                                   2               355  
2                                   1               365  
3                                   1               194  
4                                   1                 0  
...                               ...               ...  
48890                               2                 9  
48891                               2                36  
48892                               1                27  
48893                               6                 2  
48894                               1                23  

[48895 rows x 10 columns]

In [11]:
#Q1 Answer

In [12]:
df_sel_col['neighbourhood_group'].mode()

0    Manhattan
dtype: object

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
df_full_train, df_test = train_test_split(df_sel_col,test_size = 0.2, random_state = 42)
df_train, df_val = train_test_split(df_full_train, test_size = 0.25, random_state = 42)

In [15]:
len(df_train), len(df_val), len(df_test)

(29337, 9779, 9779)

In [16]:
df_train = df_train.reset_index(drop = True)
df_val = df_val.reset_index(drop = True)
df_test = df_test.reset_index(drop = True)

y_train = df_train.price
y_val = df_val.price
y_test = df_test.price

del df_train['price']
del df_val['price']
del df_test['price']

In [17]:
df_train.columns

Index(['neighbourhood_group', 'room_type', 'latitude', 'longitude',
       'minimum_nights', 'number_of_reviews', 'reviews_per_month',
       'calculated_host_listings_count', 'availability_365'],
      dtype='object')

In [18]:
df_train.dtypes

neighbourhood_group                object
room_type                          object
latitude                          float64
longitude                         float64
minimum_nights                      int64
number_of_reviews                   int64
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
dtype: object

In [19]:
numerical = ['latitude', 'longitude',
       'minimum_nights', 'number_of_reviews', 'reviews_per_month',
       'calculated_host_listings_count', 'availability_365']

In [20]:
#Q2 Answer

cor_num = df_train[numerical].corr().unstack().sort_values(ascending = False).drop_duplicates()

cor_num



latitude                        latitude                          1.000000
number_of_reviews               reviews_per_month                 0.590374
availability_365                calculated_host_listings_count    0.225913
                                number_of_reviews                 0.174477
                                reviews_per_month                 0.165376
                                minimum_nights                    0.138901
longitude                       reviews_per_month                 0.134642
calculated_host_listings_count  minimum_nights                    0.118647
availability_365                longitude                         0.083666
longitude                       latitude                          0.080301
                                number_of_reviews                 0.055084
latitude                        minimum_nights                    0.027441
calculated_host_listings_count  latitude                          0.019375
latitude                 

In [21]:
y_train

0         99
1         57
2         70
3        130
4        110
        ... 
29332     50
29333    125
29334    299
29335     65
29336     92
Name: price, Length: 29337, dtype: int64

In [22]:
above_average = [ ]

for price in y_train:
    if price >= 152:
        ab_ave = 1
    else: ab_ave = 0
    above_average.append(ab_ave)
        
above_average
        

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,


In [23]:
df_train['above_average'] = above_average
df_train.T

0             1      \
neighbourhood_group                    Brooklyn     Manhattan   
room_type                       Entire home/apt  Private room   
latitude                                40.7276      40.70847   
longitude                             -73.94495     -74.00498   
minimum_nights                                3             1   
number_of_reviews                            29             0   
reviews_per_month                           0.7           0.0   
calculated_host_listings_count               13             1   
availability_365                             50             7   
above_average                                 0             0   

                                          2                3      \
neighbourhood_group                       Bronx         Brooklyn   
room_type                       Entire home/apt  Entire home/apt   
latitude                               40.83149         40.66448   
longitude                             -73.92766        -73.99407   
minimum_nights                               40                2   
number_of_reviews                             0                3   
reviews_per_month                           0.0             0.08   
calculated_host_listings_count                1                1   
availability_365                              0                0   
above_average                                 0                0   

                                       4                5             6      \
neighbourhood_group                Manhattan        Manhattan      Brooklyn   
room_type                       Private room  Entire home/apt  Private room   
latitude                            40.74118         40.75183      40.69855   
longitude                          -74.00012        -73.99633     -73.91394   
minimum_nights                             1               30             3   
number_of_reviews                         48                0             2   
reviews_per_month                        1.8              0.0          0.31   
calculated_host_listings_count             2                1             1   
availability_365                          67              167           365   
above_average                              0                0             0   

                                          7             8             9      \
neighbourhood_group                   Manhattan      Brooklyn        Queens   
room_type                       Entire home/apt  Private room  Private room   
latitude                               40.82734      40.70473      40.76176   
longitude                             -73.94718     -73.92069     -73.76511   
minimum_nights                                4             3            31   
number_of_reviews                             3            33             0   
reviews_per_month                          1.13          2.47           0.0   
calculated_host_listings_count                1             1             1   
availability_365                              6             7            69   
above_average                                 0             0             0   

                                ...            29327            29328  \
neighbourhood_group             ...        Manhattan         Brooklyn   
room_type                       ...  Entire home/apt  Entire home/apt   
latitude                        ...         40.74894         40.71111   
longitude                       ...        -73.98673        -73.96299   
minimum_nights                  ...                5                4   
number_of_reviews               ...               28               12   
reviews_per_month               ...             3.13             0.37   
calculated_host_listings_count  ...                1                1   
availability_365                ...                0                5   
above_average                   ...                1                0   

                                 

In [24]:
#Q3 Answer
from sklearn.metrics import mutual_info_score

In [25]:
mutual_info_score(df_train.above_average, df_train.neighbourhood_group)

0.04650605348506435

In [26]:
mutual_info_score(df_train.above_average, df_train.room_type)

0.14322617342090396

In [27]:
def mutual_info_score_price(series):
    return mutual_info_score(series, df_train.above_average)

In [28]:
categorical = ['neighbourhood_group', 'room_type']
mi = df_train[categorical].apply(mutual_info_score_price)
mi.sort_values(ascending = False)

room_type              0.143226
neighbourhood_group    0.046506
dtype: float64

In [29]:
#Q4 Answer

from sklearn.feature_extraction import DictVectorizer

In [30]:
dv = DictVectorizer(sparse=False)

train_dict = df_train[categorical + numerical].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

val_dict = df_val[categorical + numerical].to_dict(orient='records')
X_val = dv.transform(val_dict)

In [31]:
X_train

array([[ 50.     ,  13.     ,  40.7276 , ...,   1.     ,   0.     ,
          0.     ],
       [  7.     ,   1.     ,  40.70847, ...,   0.     ,   1.     ,
          0.     ],
       [  0.     ,   1.     ,  40.83149, ...,   1.     ,   0.     ,
          0.     ],
       ...,
       [ 88.     ,   1.     ,  40.79994, ...,   0.     ,   1.     ,
          0.     ],
       [  0.     ,   1.     ,  40.69585, ...,   0.     ,   1.     ,
          0.     ],
       [281.     ,   2.     ,  40.64438, ...,   1.     ,   0.     ,
          0.     ]])

In [32]:
dv.get_feature_names()

['availability_365',
 'calculated_host_listings_count',
 'latitude',
 'longitude',
 'minimum_nights',
 'neighbourhood_group=Bronx',
 'neighbourhood_group=Brooklyn',
 'neighbourhood_group=Manhattan',
 'neighbourhood_group=Queens',
 'neighbourhood_group=Staten Island',
 'number_of_reviews',
 'reviews_per_month',
 'room_type=Entire home/apt',
 'room_type=Private room',
 'room_type=Shared room']

In [33]:
from sklearn.linear_model import LogisticRegression

In [34]:
model = LogisticRegression(solver='liblinear', C=1.0, random_state=42, max_iter = 1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [35]:
model_val = LogisticRegression(solver='liblinear', C=1.0, random_state=42, max_iter = 1000)
model_val.fit(X_val, y_val)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [36]:
model.coef_[0].round(3)

array([ 1.000e-03, -1.000e-03,  5.300e-02,  1.400e-01,  3.000e-03,
        6.190e-01,  6.210e-01, -6.180e-01, -5.670e-01, -5.500e-02,
        1.000e-03,  1.030e-01, -7.820e-01, -3.230e-01,  1.105e+00])

In [37]:
y_pred = model_val.predict(X_val)
y_pred

array([ 50, 200, 125, ..., 100,  50, 150], dtype=int64)

In [38]:
pred_price = (y_pred >= 152)

pred_price


array([False,  True, False, ..., False, False, False])

In [39]:
(y_val == y_pred).mean()

0.07597913897126496

In [40]:
above_average_pred = [ ]

for price in y_pred:
    if price >= 152:
        ab_ave_pred = 1
    else: ab_ave_pred = 0
    above_average_pred.append(ab_ave_pred)
        
above_average_pred


above_average_val = [ ]

for price in y_val:
    if price >= 152:
        ab_ave_val = 1
    else: ab_ave_val = 0
    above_average_val.append(ab_ave_val)
        
above_average_val


df_pred = pd.DataFrame()
df_pred['prediction'] = y_pred
df_pred['actual'] = y_val
df_pred['above_average_pred'] = above_average_pred
df_pred['above_average_val'] = above_average_val

df_pred['correct'] = df_pred.above_average_pred == df_pred.above_average_val

df_pred.correct.mean().round(2)


0.72

In [51]:
#Q5 Answer(Incomplete)
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
import seaborn as sns
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.ensemble import RandomForestClassifier

In [57]:
X_df = df_train.drop(['above_average'], axis =1)

X = X_df.drop(['neighbourhood_group'], axis = 1)

Y = df['neighbourhood_group']

X = pd.get_dummies(X, prefix_sep='_')

Y = LabelEncoder().fit_transform(Y)

X2 = StandardScaler().fit_transform(X)

X_Train, X_Val, Y_Train, Y_Val = train_test_split(X2, Y, test_size = 0.25, random_state = 42)

ValueError: Found input variables with inconsistent numbers of samples: [29337, 48895]